- AUTHORS
- reversion_compare/admin.py
- reversion_compare/templates/reversion-compare/compare.html
- reversion_compare_test_project/manage.py
Still needs appropriate tests for the new, just submitting the request as an FYI. There is a little more work that needs to be done to write the tests.
The reverse foreign key (ManyToOne) behaves very similar to the ManyToOne, so it reuses a lot of that code. However, the `related` property doesn't have a `get_internal_type` or `rel` methods, hence the extra checks.
> Reverse foreign key

- .travis.yml
- reversion_compare/admin.py
- tests/test_custom_model.py
- tests/test_factory_car_reverse_models.py
Added Django 1.8 support ( #33) , corrected bug #34
> Django 1.8 support

- AUTHORS
- reversion_compare/admin.py
Django 1.8 shows the error message:
```
(testapp)luzfcb@luzfcb:~/projects/testapp$ python manage.py check
/home/luzfcb/virtualenvs/testapp/lib/python3.4/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
"Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)
System check identified no issues (0 silenced).
```
because in django 1.9, the module `django.contrib.admin.util` was renamed `django.contrib.admin.utils`
> Update admin.py to avoid RemovedInDjango19Warning

- AUTHORS
- reversion_compare/admin.py
- tests/admin.py
- tests/models.py
- tests/test_onetoone_field.py
- tests/test_utils/test_data.py
The code is almost the same as @aemdy fix, https://github.com/aemdy/django-reversion-compare/commit/da60d7873bbd8fb212f7f076a68b0b52e297796e. Just a bit more nicely structured and with a proper commit message.
This should fix: #36
Note that there are other problems in the code base that will most likely cause a comparison to still fail, such as #41.
> One to one field custom related name fix

- AUTHORS
- README.creole
- reversion_compare/admin.py
- reversion_compare/compare.py
- reversion_compare/mixins.py
- reversion_compare/templates/reversion-compare/action_list_partial.html
- reversion_compare/templates/reversion-compare/compare.html
- reversion_compare/templates/reversion-compare/compare_links_partial.html
- reversion_compare/templates/reversion-compare/compare_partial.html
- reversion_compare/templates/reversion-compare/object_history.html
- reversion_compare/views.py
- tests/templates/tests/simplemodel_detail.html
- tests/test_variant_model.py
- tests/test_view.py
- tests/urls.py
- tests/views.py
Changes:
* Refactor admin.py by extracting common code between admin and non-admin view and putting it to two new modules: mixins.py (for view mixins) and compare.py (for compare objects)
* Implement a HistoryCompareDetailView CBV that can be used as a normal DetailView to both display the history and select-version-form *and* the changes of the selected versions
* Fix tests so that they run under windows and add test for new CBV (by copying the tests for the SimpleModel -- probably this could be refactored a bit)
* Update README and AUTOHRS
> Admin history/view for non-admin views (issue #46)

- reversion_compare/admin.py
- reversion_compare/compare.py
- setup.py
- tests/models.py
- tests/test_custom_model.py
- tests/test_factory_car_models.py
- tests/test_factory_car_reverse_models.py
- tests/test_onetoone_field.py
- tests/test_person_pet_models.py
- tests/test_simple_model.py
- tests/test_utils/test_cases.py
- tests/test_utils/test_data.py
- tests/test_variant_model.py
- tests/test_view.py
`import reversion` no longer works on the latest `django-reversion`.
I also changed `setup.py` so that it doesn't insist on downgrading `Django`.
> Django 1.9 and django-reversion 1.10.0 support

- reversion_compare/compare.py
- reversion_compare/locale/el/LC_MESSAGES/django.po
- reversion_compare/locale/nl/LC_MESSAGES/django.po
This avoids storing an ugettext value in self.version.
It's value got parsed in `ids = [int(v) for v in self.value]`
causing an `int("F")` call that fails.
Instead, a sentinal value is introduced that can be recognized in the
code, yet output a meaningful message when it's shown to the user.
Fixes #44 
This is a rebased version of #54
> Fix Python error when ManyToMany relations didn't exist.

- reversion_compare/compare.py
I have a model (Station) that uses UUID as pk, and it has an ManyToMany relation to a model (Entity) that uses integers as pk. With current implementation I get an exception because Station.has_int_pk() returns False (as it should), so ids is None when we call `get_many_to_something()`. It should check if the related model has integers as pk, because it's the related model ids when want in our query.
I guess there should be an else statement where ids is set to `self.value`, if the related model uses string as pk?
> Check if related model has an integer as pk for ManyToMany fields.

- reversion_compare/compare.py
- tests/models.py
- tests/test_utils/test_data.py
- tests/test_variant_model.py
Hi, @jedie!
Thanks for great package.
Tired of of displaying weird and unclear symbols in choices field and fixed this.
Also updated your test with new field check.
> Added choices field representation

- reversion_compare/admin.py
`django.conf.urls.patterns` is deprecated and will be removed in Django 1.10.
> Remove unused and deprecated `patters`

- README.creole
It's a 404, looks like the whole forum section is gone from pylucid.
> README - remove forum link

- .travis.yml
- AUTHORS
- reversion_compare/admin.py
- reversion_compare/compare.py
- reversion_compare/forms.py
- reversion_compare/helpers.py
- reversion_compare/mixins.py
- reversion_compare/reversion_api.py
- reversion_compare/views.py
- setup.py
- tests/admin.py
- tests/models.py
- tests/test_custom_model.py
- tests/test_factory_car_models.py
- tests/test_factory_car_reverse_models.py
- tests/test_onetoone_field.py
- tests/test_person_pet_models.py
- tests/test_settings.py
- tests/test_simple_model.py
- tests/test_utils/test_cases.py
- tests/test_utils/test_data.py
- tests/test_variant_model.py
- tests/test_view.py
- tests/views.py
- Sorry for the large PR, but included is some pep8 cleanup and optimizations
- Unit Tests pass locally
- Testing ok with django-reversion 2.04 and Oracle as DB
> Update for django-reversion 2.04

- setup.py
Found them sitting in my installed packages :scream:
Checked in shell:
```
In [2]: find_packages()
Out[2]:
['reversion_compare',
'tests',
'tests.management',
'tests.test_utils',
'tests.management.commands']
In [3]: find_packages(exclude=['tests', 'tests.*'])
Out[3]: ['reversion_compare']
```
> setup.py - don't package tests

- reversion_compare/mixins.py
- reversion_compare_tests/admin.py
- reversion_compare_tests/models.py
- reversion_compare_tests/test_template_field_model.py
- reversion_compare_tests/test_utils/test_data.py
When model has field with name "template" and has ForeignKey type next code
```
def _get_compare_func(suffix):
func_name = "compare_%s" % suffix
if hasattr(self, func_name):
func = getattr(self, func_name)
if callable(func):
return func
```
get `compare_template` field from `VersionAdmin` class which is `str` object, not callable.
> Fix case when model has template field which is ForeignKey

- reversion_compare/admin.py
Using the 'render' function to ensure the execution of context processors properly
> Using the 'render' function to ensure the execution of context processors properly

- reversion_compare/compare.py
This pull request fixes #10 
It's far away to be a proper fix though as it just works around the issue by completely ignoring tags from taggit. Hence changes to tags won't show up in the comparison.
> Work around a type error triggered by taggit

- .travis.yml
- reversion_compare/compare.py
- reversion_compare_tests/models.py
- reversion_compare_tests/settings.py
- reversion_compare_tests/test_custom_model.py
- reversion_compare_tests/urls.py
- tox.ini
This adds compatibility to Django 2.0
The change also includes add django2 to tox so it runs the tests against it as well.
> Add Django 2.0 compatibility

- reversion_compare/compare.py
In case of relation to model with primary key which is named differently as `id`, it is raising the following error when comparing revisions.
```
'ModelName' object has no attribute 'id'
../site-packages/reversion_compare/compare.py in <setcomp>, line 130
```
`.pk` should be used.
> Use .pk instead of .id when referring to related object.

- AUTHORS
- reversion_compare/compare.py
I just got a ping because  #114 got merged. 
Thanks to @baffolobill's fork I noticed that reversion actually has a check to see if a model is registered. So I used that instead of the uglier try/except. Additionally to @baffolobill's fork, I still use `REVERSION_COMPARE_IGNORE_NOT_REGISTERED`.
Unfortunately I forgot to update my initial PR :-( so here it goes again
(further fixes #103)
> actually check if model is registered

- reversion_compare/compare.py
- reversion_compare_tests/models.py
Adds support for django 3.0
See https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis
The README indicates that python2 is not supported in the current
version, so there shouldn't by any issues removing these.
> Remove python2 compatibility decorators

- reversion_compare/templates/reversion-compare/action_list_partial.html
This is the port of the commit https://github.com/etianen/django-reversion/commit/ae82a832bd353d83ab281305deb0967e9110c503 from the original django-reversion template.
Without this patch, the `User` column in the object history view is always empty if your User model doesn't have a username or full name.
> Show username and full name from custom user model

- reversion_compare/admin.py
https://github.com/darklow/django-suit/issues/633
https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.AdminSite.each_context
> Fix django-suit NoneType is not iterable

- .github/workflows/pythonapp.yml
Why will be lxml installed here:
https://github.com/jedie/django-reversion-compare/runs/454780186?check_suite_focus=true ???
> lock + show --tree before install to find install problems:

- pyproject.toml
The README says it's compatible with Django 3.0 but the pyproject.toml only specifies 2.2.*
> Add Django version 3.0 to the project dependencies

- pyproject.toml
- pytest.ini
- tox.ini
* Add `Django==3.1` to tox test matrix
* Remove direct Django dependency (as suggested in #131)
* Fix `pytest` arguments after [6.0 released](https://docs.pytest.org/en/stable/changelog.html#id19)
> Allow use Django>=3.1

- reversion_compare/admin.py
Fixes the warning 
`RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().`
by using modern `path` URL function
> Fix django.conf.urls.url() is deprecated

- reversion_compare/helpers.py
- reversion_compare/templates/reversion-compare/compare.html
- reversion_compare_tests/test_helpers.py
- reversion_compare_tests/test_variant_model.py
Squashed commit of the following:
commit d48d60cb40090c7fb2c8b6a97a134100e12f07a0
Author: Dan Bader <mail@dbader.org>
Date:   Mon Dec 14 09:55:24 2020 -0800
Make diff lines full-width
commit b17c63359dcbd9ac0c704a18c11875202d7d7fbe
Author: Dan Bader <mail@dbader.org>
Date:   Sun Dec 13 18:51:59 2020 -0800
Cleanup; add docstrings
commit ad0383cdc4e1822d014483839c7d69e9747c0548
Author: Dan Bader <mail@dbader.org>
Date:   Sun Dec 13 12:59:45 2020 -0800
Update diff color scheme
commit 9f4ac80d2991dbb8c87614ad1d4388711cbc0e4e
Author: Dan Bader <mail@dbader.org>
Date:   Sun Dec 13 12:59:28 2020 -0800
Fix diff_match_patch_pretty_html HTML spans
commit 1ed6665be6f4359b8a89e153383fc9f6b89cbe4b
Author: Dan Bader <mail@dbader.org>
Date:   Sat Dec 12 16:39:05 2020 -0800
Fix line end handling, update …
> Multiline diff formatting improvements #137

- reversion_compare/templates/reversion-compare/compare.html
@jedie Quick heads up, I just upgraded to 0.13.1 and noticed that this change breaks line wrapping. Here's what it's supposed to look like (with `white-space: pre-line`):
Here's what it currently looks like in 0.13.1 (no `white-space: pre-line`):
Without `white-space: pre-line`, long lines extend past the max-width instead of wrapping, and the diff looks broken as a result.
There was probably another reason why you removed the `white-space` setting? Or was it accidental? Here's a quick PR to ad it back.
(https://github.com/jedie/django-reversion-compare/pull/144#discussion_r573092921)
> Fix line breaks on long lines in diff

- reversion_compare/admin.py
This should prevent those admin pages from executing potentially thousands of queries. Refs #152.
> Speed up Revision/Version admin with raw_id_fields and list_select_related

- reversion_compare/helpers.py
This seems to generate much cleaner diffs for long texts with many edits. With `checklines=False` we usually end up with a "delete old text, insert new text" diff that's not very useful.
`checklines=True` is the default in `diff-match-patch`.  So I'm guessing there was a reason that `checklines` was disabled, maybe you can chime in on that @jedie. 
We could shorten this even further to just:
```python
diff = dmp.diff_main(value1, value2)
```
* https://github.com/google/diff-match-patch
* `checklines` flag definition: https://github.com/google/diff-match-patch/blob/62f2e689f498f9c92dbc588c58750addec9b1654/python3/diff_match_patch.py#L85
> Enable diff-match-patch "checklines" mode for better diffs

- README.md
- pyproject.toml
- requirements.txt
- reversion_compare/__init__.py
We use rich.pretty.pretty_repr() for pretty format fallback in `compare.CompareObject._obj_repr()` so it's needed to be installed: Move it from `dev` to `normal` requirements.
> Bugfix packaging: We use rich in production code
